// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ZniH3wqehEMCP1OOdZGzVzPDoL_fzbA',
    appId: '1:15015081208:web:ecbd50a7f8b4fc9b37f70d',
    messagingSenderId: '15015081208',
    projectId: 'scheduler-81d76',
    authDomain: 'scheduler-81d76.firebaseapp.com',
    storageBucket: 'scheduler-81d76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh9hYIUTmgIyAkub3fc_tGqEGJ5QPnkzs',
    appId: '1:15015081208:android:8db2533b38a1994937f70d',
    messagingSenderId: '15015081208',
    projectId: 'scheduler-81d76',
    storageBucket: 'scheduler-81d76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwiEgXPno87rT-42iQyduN6uyy3PPSsFM',
    appId: '1:15015081208:ios:122848f4bb2fe35537f70d',
    messagingSenderId: '15015081208',
    projectId: 'scheduler-81d76',
    storageBucket: 'scheduler-81d76.appspot.com',
    iosBundleId: 'com.example.schedulerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwiEgXPno87rT-42iQyduN6uyy3PPSsFM',
    appId: '1:15015081208:ios:d4072aa43093747137f70d',
    messagingSenderId: '15015081208',
    projectId: 'scheduler-81d76',
    storageBucket: 'scheduler-81d76.appspot.com',
    iosBundleId: 'com.example.schedulerApp.RunnerTests',
  );
}
